INSERT INTO projects (title, slug, description, tech_tags, live_demo_url, github_url, thumbnail_url, status) VALUES
('Intelligent Document Flow', 'intelligent-document-flow', 'Built an intelligent document processing system that uses OCR and NLP to extract structured data from unstructured documents. The system automates data entry, reduces manual processing time by 70%, and integrates with existing enterprise workflows.', ARRAY['Python', 'Tesseract OCR', 'spaCy', 'FastAPI'], NULL, NULL, NULL, 'published'),
('AI Knowledge Assistant', 'ai-knowledge-assistant', 'Developed a retrieval-augmented generation (RAG) chatbot that answers questions from internal company documents. Uses vector embeddings for semantic search and maintains context across conversations.', ARRAY['LangChain', 'OpenAI', 'ChromaDB', 'React'], NULL, NULL, NULL, 'published'),
('Workflow Insights', 'workflow-insights', 'Created an analytics dashboard that visualizes business process metrics and identifies bottlenecks. Uses machine learning to predict process outcomes and suggest optimizations.', ARRAY['Python', 'Pandas', 'Scikit-learn', 'Next.js'], NULL, NULL, NULL, 'published'),
('Sentiment Analyzer', 'sentiment-analyzer', 'Built a real-time sentiment analysis system that processes customer reviews and social media comments. Classifies feedback into positive, negative, and neutral categories with 92% accuracy.', ARRAY['Python', 'Transformers', 'FastAPI', 'PostgreSQL'], NULL, NULL, NULL, 'published'),
('Image Classifier', 'image-classifier', 'Developed a custom image classification model for detecting products in retail environments. Trained on 10,000+ images with transfer learning achieving 95% accuracy.', ARRAY['Python', 'TensorFlow', 'OpenCV', 'Docker'], NULL, NULL, NULL, 'published'),
('Predictive Maintenance', 'predictive-maintenance', 'Built an ML pipeline that predicts equipment failures before they occur. Uses sensor data and historical maintenance records to forecast failures with 85% accuracy.', ARRAY['Python', 'XGBoost', 'Airflow', 'AWS'], NULL, NULL, NULL, 'published'),
('Chatbot Framework', 'chatbot-framework', 'Created a reusable chatbot framework supporting multi-turn conversations with context retention. Includes intent recognition, entity extraction, and response generation.', ARRAY['Python', 'Rasa', 'FastAPI', 'Redis'], NULL, NULL, NULL, 'published'),
('Data Pipeline', 'data-pipeline', 'Designed an automated ETL pipeline that ingests, transforms, and prepares data for ML model training. Handles data validation, feature engineering, and versioning.', ARRAY['Python', 'Apache Spark', 'Airflow', 'S3'], NULL, NULL, NULL, 'published'),
('Recommendation Engine', 'recommendation-engine', 'Built a recommendation engine that provides personalized content suggestions based on user behavior and preferences. Uses collaborative filtering and content-based approaches.', ARRAY['Python', 'Surprise', 'FastAPI', 'Redis'], NULL, NULL, NULL, 'published');
